export {default as AdminLayout} from './AdminLayout'
export {default as Dashboard} from './Dashboard'
export {default as ManageOrder} from './ManageOrder'
export {default as ManageProduct} from './ManageProduct'
export {default as ManageUser} from './ManageUser'
export {default as ManageCategory} from './ManageCategory'
export {default as ManageAuthor} from './ManageAuthor'