# Sử dụng image Node.js chính thức
FROM node:20.15.1

# Thiết lập thư mục làm việc trong container
WORKDIR /usr/src

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các phụ thuộc
RUN npm install --production

# Sao chép toàn bộ mã nguồn vào thư mục làm việc
COPY . .

# Expose cổng mà ứng dụng sẽ chạy
EXPOSE 3000

# Chạy ứng dụng
CMD ["node", "server.js"]