name: Full Stack CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: server/package-lock.json # ✅ Đường dẫn đúng của package-lock.json

      - name: Install dependencies
        working-directory: server # ✅ Chạy lệnh trong thư mục server
        run: npm ci

      - name: Build project
        working-directory: server # ✅ Sửa từ backend → server
        run: npm run build --if-present

      - name: Run tests
        working-directory: server
        run: npm test --if-present
